#define TinselLogWordsPerMsg 4
#define TinselMeshYLen 1
#define TinselFPDivLatency 14
#define TinselMeshYBits 2
#define TinselLogBytesPerDRAM 31
#define TinselLogBytesPerLine 5
#define TinselCoresPerFPU 4
#define TinselLogFlitsPerThread 6
#define TinselLogMailboxesPerBoard 4
#define TinselFPUsPerBoard 16
#define TinselFPUOpMaxLatency 14
#define TinselLogFPUsPerBoard 4
#define TinselMacLatency 100
#define TinselLogCoresPerFPU 2
#define TinselLogCoresPerBoard 6
#define TinselTargetBoard '"DE5"'
#define TinselLogBeatsPerLine 0
#define TinselWordsPerBeat 8
#define TinselLogBeatsPerDRAM 26
#define TinselLogThreadsPerFPU 6
#define TinselLogReliableLinkRecvBufferSize 9
#define TinselLogWordsPerBeat 3
#define TinselLogDRAMsPerBoard 1
#define TinselLogTransmitBufferLen 2
#define TinselFPConvertLatency 6
#define TinselDeviceFamily '"Stratix V"'
#define TinselLogMsgsPerThread 4
#define TinselLogThreadsPerCore 4
#define TinselFPCompareLatency 3
#define TinselFPAddSubLatency 14
#define TinselLogLinesPerMem 27
#define TinselFPMultLatency 11
#define TinselDRAMLatency 20
#define TinselLogBytesPerFlit 4
#define TinselThreadsPerCore 16
#define TinselMaxFlitsPerMsg 4
#define TinselBeatWidth 256
#define TinselLogOffChipRAMBaseAddr 11
#define TinselLogCoresPerMailbox 2
#define TinselLogThreadsPerBoard 10
#define TinselLogMacRecvBufferSize 5
#define TinselLogWordsPerLine 3
#define TinselBeatBurstWidth 1
#define TinselLogInstrsPerCore 11
#define TinselLinkTimeout 1024
#define TinselThreadsPerBoard 1024
#define TinselBeatsPerLine 1
#define TinselLogThreadsPerDRAM 9
#define TinselLogMaxFlitsPerMsg 2
#define TinselDCacheLogSetsPerThread 3
#define TinselMaxThreads 16384
#define TinselLogDCachesPerDRAM 3
#define TinselSharedInstrMem False
#define TinselWordsPerFlit 4
#define TinselMeshXLen 3
#define TinselThreadsPerDRAM 512
#define TinselLogBytesPerDRAMPartition 21
#define TinselIntMultLatency 3
#define TinselCoresPerMailbox 4
#define TinselMailboxesPerBoard 16
#define TinselLogWordsPerFlit 2
#define TinselLogBytesPerMsg 6
#define TinselLogTransmitBufferSize 10
#define TinselDCacheLogNumWays 2
#define TinselBytesPerBeat 32
#define TinselDCachesPerDRAM 8
#define TinselDRAMLogMaxInFlight 5
#define TinselLogBeatsPerMem 27
#define TinselMaxBootImageBytes 512
#define TinselLogCoresPerDCache 2
#define TinselCoresPerDCache 4
#define TinselLogBytesPerBeat 5
#define TinselBitsPerLine 256
#define TinselTransmitBound 20
#define TinselWordsPerLine 8
#define TinselMeshXBits 2
#define TinselDRAMsPerBoard 2
#define TinselLogThreadsPerMailbox 6
#define TinselLogLinesPerDRAM 26
#define TinselCoresPerBoard 64
#define TinselBytesPerDRAM 2147483648
#define TinselLogBytesPerMem 32
