#define TinselLogBytesPerDRAM 31
#define TinselMeshYLen 1
#define TinselFPDivLatency 14
#define TinselMeshYBits 2
#define TinselLogThreadsPerDRAM 6
#define TinselLogBytesPerLine 5
#define TinselLogReceiveBufferSize 5
#define TinselLineSize 256
#define TinselCoresPerFPU 4
#define TinselLogFlitsPerThread 6
#define TinselLogMailboxesPerBoard 1
#define TinselFPUsPerBoard 2
#define TinselFPUOpMaxLatency 14
#define TinselLogFPUsPerBoard 1
#define TinselMacLatency 100
#define TinselLogCoresPerFPU 2
#define TinselLogCoresPerBoard 3
#define TinselTargetBoard '"DE5"'
#define TinselLogBeatsPerLine 0
#define TinselWordsPerBeat 8
#define TinselLogBeatsPerDRAM 26
#define TinselLogThreadsPerFPU 6
#define TinselLogWordsPerMsg 4
#define TinselLogWordsPerBeat 3
#define TinselLogDRAMsPerBoard 1
#define TinselLogTransmitBufferLen 2
#define TinselFPConvertLatency 6
#define TinselDeviceFamily '"Stratix V"'
#define TinselLogMsgsPerThread 4
#define TinselLogThreadsPerCore 4
#define TinselFPCompareLatency 3
#define TinselFPAddSubLatency 14
#define TinselFPMultLatency 11
#define TinselDRAMLatency 20
#define TinselLogBytesPerFlit 4
#define TinselThreadsPerCore 16
#define TinselMaxFlitsPerMsg 4
#define TinselBeatWidth 256
#define TinselLogCoresPerMailbox 2
#define TinselLogThreadsPerBoard 7
#define TinselLogWordsPerLine 3
#define TinselBeatBurstWidth 1
#define TinselLogInstrsPerCore 11
#define TinselLinkTimeout 1024
#define TinselThreadsPerBoard 128
#define TinselBeatsPerLine 1
#define TinselLogMaxFlitsPerMsg 2
#define TinselDCacheLogSetsPerThread 3
#define TinselMaxThreads 2048
#define TinselLogDCachesPerDRAM 0
#define TinselWordsPerFlit 4
#define TinselMeshXLen 1
#define TinselThreadsPerDRAM 64
#define TinselLogBytesPerDRAMPartition 21
#define TinselIntMultLatency 3
#define TinselCoresPerMailbox 4
#define TinselMailboxesPerBoard 2
#define TinselLogWordsPerFlit 2
#define TinselLogBytesPerMsg 6
#define TinselLogTransmitBufferSize 10
#define TinselDCacheLogNumWays 2
#define TinselBytesPerBeat 32
#define TinselDCachesPerDRAM 1
#define TinselDRAMLogMaxInFlight 4
#define TinselMaxBootImageBytes 512
#define TinselLogCoresPerDCache 2
#define TinselCoresPerDCache 4
#define TinselLogBytesPerBeat 5
#define TinselTransmitBound 20
#define TinselWordsPerLine 8
#define TinselMeshXBits 2
#define TinselDRAMsPerBoard 2
#define TinselLogThreadsPerMailbox 6
#define TinselLogLinesPerDRAM 26
#define TinselCoresPerBoard 8
#define TinselBytesPerDRAM 2147483648
#define TinselLogScratchpadBytes 11
